### ISSUE TITLE
Update docker2singularity to not require docker engine

### ISSUE THREAD

**Issue by vsoch** [singularityware/docker2singularity#12]
Specifically, we want the docker2singularity image to provide a Dockerized access to native Singularity, which uses the Docker Registry API to generate images. This is to guarantee that images created are equivalent, which (I don't believe) is currently the case! See https://github.com/singularityware/singularity/issues/396#issuecomment-265605168 for details, and this likely will fix #10

**Comment by chrisfilo** [comment]
+1 for updating docker2singularity (as long it is keeping all of the features). Fixing permissions, setting the environment, creating mountpoints, as well as handling runscripts was there to maximize the chances of creating a fully functional image out of the box for most docker images.

I would also wanna point out that the current implementation allows users to convert Docker images that are not in Docker Hub - a useful feature that would be nice to preserve.

**Comment by vsoch** [comment]
+1 +1

**Comment by chrisfilo** [comment]
Also as the saying goes - "if it's ain't broken don't fix it". As long as Singularity will provide backward compatibility for running images from old versions (which it definitely should) the current version of docker2singularity will serve its purpose. I don't think there is an urgent need to do this refactoring.

**Comment by vsoch** [comment]
I'm going to close this - I don't anticipate it will be useful moving forward.
