### ISSUE TITLE
remove reliance on privileged containers

### ISSUE THREAD

**Issue by ccraddock** [singularityware/docker2singularity#13]
docker2singularity must run in a privileged containers due to its use of /dev/loop0 (and possibly other reasons). This makes it impossible to run in circleCI, which explicitly runs its containers without privileges. It would be awesome if a workaround could be found to remove the need on privilege so that we can do singularity deployments from circleCI.

**Comment by vsoch** [comment]
@ccraddock is this still an issue for you? Note that you can pull a docker container directly to singularity, without sudo:

```
singularity pull docker://godlovedc/lolcow
Creating empty 495MiB image file: ./lolcow.img
Formatting image with ext3 file system
Image is done: ./lolcow.img
...
```
and for your own wellbeing, please run the image after you pull it :)

**Comment by vsoch** [comment]
I'm closing here, as Singularity can pull from docker without priviledges (and this issue is also very old!) @ccraddock please let us know if you need any further help!
