### ISSUE TITLE
convert directly into directory dump instead of image file

### ISSUE THREAD

**Issue by thdesy** [singularityware/docker2singularity#21]
Hi Chris,

it would be great if one could have an option/flag to convert a Docker image into a Singularity directory in addition to the flat image file (which might make an automatized roll out to CVMFS easier)

Thanks,
  Thomas

**Comment by chrisfilo** [comment]
This should be possible and potentially would not be hard. Would you like to take a stab at it?

**Comment by thdesy** [comment]
yes, I can give it a try. I had already peaked into docker2singularity.sh if one could do a rsync or so from a mounted image.
However, not in the coming two weeks, since I will be on vacation ;)

**Comment by vsoch** [comment]
hey @thdesy is this something you are still interested in? With Singularity 2.4 you can build right into a directory, so it may not be needed here:

```
sudo singularity build folder/ docker://ubuntu
```

**Comment by thdesy** [comment]
Hi Vanessa,

many thanks for the info - I will have a look! :)

Cheers and thanks,
  Thomas

**Comment by vsoch** [comment]
hey @thdesy this is long since supported for Singularity 2.4, and is now (also) available for the version 2.5.1 branch. I'm closing this issue and please re-open (or open a fresh one) if you have any trouble. Thanks!
