### ISSUE TITLE
How to set output image file name?

### ISSUE THREAD

**Issue by stevekm** [singularityware/docker2singularity#29]
When I run this, I get an image file with a random string appended, like this:

`stevekm_phoenix-demo_demo1-2018-03-15-94a3b28d5358.img`

I would rather be able to tell it what to name the output file, or at the least  turn off the random string, so that if I run the same command repeatedly (e.g. in a Makefile) the same file gets produced & overwritten every time. 

In this case, I am building it off the container [here](https://github.com/stevekm/NYU-phoenix-docker-singularity-nextflow-demo/tree/7680e96c2359e7f9d65e9c0a6134d5c6db68fdb4/containers/demo1) it would be better if the output was named something like `stevekm_phoenix-demo_demo1.img`

**Comment by vsoch** [comment]
hey @stevekm ! if you would like to test, I've added this feature for the v2.5 branch here https://github.com/singularityware/docker2singularity/pull/30 See the PR comments for the example.
