### ISSUE TITLE
failure when using -f or -w options

### ISSUE THREAD

**Issue by cattoni** [singularityware/docker2singularity#43]
First of all nice tool, thanks!

The problem is that current version of docker2singularity.sh fails with flags -f|--folder and -w|--writable because two "shift" commands are invocated (one "shift" is enough because such flags have no arguments).

So please:
 - remove lines 84 and 89
 - correct the typo in line 86 (change the misspelled "-wrtiable" with "--writable")

Best.

**Comment by vsoch** [comment]
hey @cattoni I've just updated all branches and master with various fixes - would you care to take a look at the branch (version of Singularity) you were/are using, and open a PR if this issue persists? I apologize for not seeing your issue until now, I hadn't been watching the repo.

**Comment by vsoch** [comment]
Closing, no response.
