### ISSUE TITLE
Error when I execute the all examples: /docker2singularity.sh: line 110: $1: unbound variable

### ISSUE THREAD

**Issue by rafaelmarconiramos** [singularityware/docker2singularity#48]
I execute the examples and receive an error from the shell script:

/docker2singularity.sh: line 110: $1: unbound variable

What is the problem?

Thanks

**Comment by vsoch** [comment]
hey @rafaelmarconiramos what branch are you using? It's probably about time we updated master to be the latest version of singularity - I am going to start work on this and will address your issue there.

**Comment by vsoch** [comment]
Master is now updated, so if you could give me a branch (version) and set of commands to reproduce your error, I can help.

**Comment by vsoch** [comment]
hey @rafaelmarconiramos any updates here? If I don't hear from you I'm going to close the issue and assume you got things working.

**Comment by vsoch** [comment]
Closing, no response.
