### ISSUE TITLE
v2.6 creates unreadable images since #58

### ISSUE THREAD

**Issue by jvansanten** [singularityware/docker2singularity#60]
Hi! For silly reasons involving permissions and firewalls, I have a CI workflow that uses docker2singularity to convert a local Docker image to Singularity format, which then gets handed off to the production system via an intermediate file server that both can connect to. For other silly reasons, the CI wipes its Docker layer cache nightly, so I always work with whatever happens to be tagged as `singularityware/docker2singularity:v2.6`.

Last week, however, the images produced by the CI stopped working with Singularity 2.6.1, printing `ERROR  : Unknown image format/type` when I try to run it. I can reproduce this with any of the subcommands. For example, on a working image:

```
singularity -v inspect ampel-v0.6.12.simg
Increasing verbosity level (2)
Singularity version: 2.6.1-dist
Exec'ing: /usr/libexec/singularity/cli/inspect.exec
VERBOSE: Set messagelevel to: 2
VERBOSE: Initialize configuration file: /etc/singularity/singularity.conf
VERBOSE: Initializing Singularity Registry
VERBOSE: No autofs bug path in configuration, skipping
VERBOSE: Found available loop device: /dev/loop37
VERBOSE: Using loop device: /dev/loop37
VERBOSE: Mounting squashfs image: /dev/loop37 -> /var/singularity/mnt/final
VERBOSE: Running command: /bin/bash
{
    "org.label-schema.singularity.build": "squashfs",
    "org.label-schema.docker.version": "18.09.6",
    "org.label-schema.schema-version": "1.0",
    "org.label-schema.singularity.build-type": "docker2singularity",
    "org.label-schema.docker.id": "sha256:bfcb5fd8d67e2c1d5ebb9e81840095cce5a17753179b4eb5697a117c3805dfdd",
    "org.label-schema.build-date": "2019-05-15-14:47:48",
    "org.label-schema.singularity.version": "2.6.0-dist",
    "org.label-schema.docker.created": "2019-05-15"
}
```

while on a recent image, I get:

```
singularity -v inspect ampel-v0.6.simg
Increasing verbosity level (2)
Singularity version: 2.6.1-dist
Exec'ing: /usr/libexec/singularity/cli/inspect.exec
VERBOSE: Set messagelevel to: 2
VERBOSE: Initialize configuration file: /etc/singularity/singularity.conf
VERBOSE: Initializing Singularity Registry
VERBOSE: No autofs bug path in configuration, skipping
VERBOSE: File is not a valid SquashFS image
VERBOSE: File is not a valid EXT3 image
```

Any idea what's going wrong here?

**Comment by vsoch** [comment]
Let me take a look - it sounds like I rebuilt 2.6 and it possibly wasn't the exact 2.6 as previously. Do you have an image I can pull from somewhere to reproduce?

**Comment by vsoch** [comment]
Here is the Singularity version that is served by the container:

```
$ docker run -it singularityware/singularity:2.6 --version
2.6.1-vault/release-2.6.9103f0155
```
It's the vault release, which is the .tar.gz that is served from the repo, and I chose that because if you look at the releases page, the actual release for 2.6.1 is gone (remaining is 2.6.0 https://github.com/sylabs/singularity/releases/tag/2.6.0). My best guess is that 2.6.1-dist (which I'm not sure where it is) is somehow different from the vaulted branch. Just curious - did you try v2.5 and does it produce the same issue? What I can do is try building a container with 2.6.0 (the official release) and have you test - if that works we can update the 2.6 branch to be 2.6.0, and then push the current v2.6 as v2.6.1. Let me know your thoughts!

**Comment by jvansanten** [comment]
v2.5 appears to produce readable images. As far as I can remember, 2.5 and 2.6 only differed in runtime features, so that probably already gets me back up and running.

I'm still mildly curious as to what went wrong, though, so can test an image made with a rebuilt 2.6 if you have one.

**Comment by vsoch** [comment]
Yes let me build one for you - I suspect there is a difference between (what used to exist) as the release, and what is now a branch (the vault).

**Comment by vsoch** [comment]
okay - I think I just found the issue! The 3.1 release was tagged with 2.6, so I believe you were building with a 3.* derivative of Singularity. The repo originally did automated builds, then Docker Hub got hacked, they re-did their entire build system (and I can't really figure it out still). So what I've just done is fixed the recipes to deploy from the branches during run of CircleCI, and that way we don't need to rely on Docker Hub working (beyond pushing to it). 

I think this was the underlying issue -> https://github.com/singularityware/docker2singularity/commit/a0f2393a728649039055f13a5b478b0b51473a6d

I've just fixed this all up (see tags here) https://cloud.docker.com/u/singularityware/repository/docker/singularityware/docker2singularity/tags and would you care to test?

```bash
$ docker run -it --entrypoint bash singularityware/docker2singularity:v2.6Unable to find image 'singularityware/docker2singularity:v2.6' locally
v2.6: Pulling from singularityware/docker2singularity
e7c96db7181b: Pull complete 
5297bd381816: Pull complete 
3a664477889c: Pull complete 
456ccbcfb7c2: Pull complete 
be49115c409f: Pull complete 
4e5a67a694a2: Pull complete 
90e35d75c5fb: Pull complete 
c7d8067f2392: Pull complete 
de3e7f56e947: Pull complete 
19c9b74d6f10: Pull complete 
Digest: sha256:ae6f3dd54c9dd78ee7a8d6e7f4d9af868a96d4761ce396c4dbd5ba414d72537b
Status: Downloaded newer image for singularityware/docker2singularity:v2.6
bash-4.4# singularity --version
2.6.0-dist
```

**Comment by jvansanten** [comment]
Indeed, the images produced with 2.6-that's-actually-2.6 are readable. Many thanks!

**Comment by vsoch** [comment]
Great! And apologies for the mishap, that was totally my fault. I'm traveling and my brain is in a squish.
