### ISSUE TITLE
Strange Error when trying to convert - addLabel.py: No such file or directory

### ISSUE THREAD

**Issue by blairjj** [singularityware/docker2singularity#68]
Jays-MacBook-Pro-2:bin bj2348$ docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:18:17 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
Jays-MacBook-Pro-2:bin bj2348$ singularity version
3.2.0-rc2

Jays-MacBook-Pro-2:bin bj2348$ docker image list
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
basilisk            latest              17b2070a17f4        13 days ago         1.08GB
centos6_cfd         latest              64a9cf2d63ba        2 weeks ago         777MB
ubuntu              latest              3556258649b2        3 weeks ago         64.2MB
centos              6                   d0957ffdf8a2        5 months ago        194MB
centos              latest              9f38484d220f        5 months ago        202MB
Jays-MacBook-Pro-2:bin bj2348$ sudo ./docker2singularity.sh basilisk
Password:

Image Format: squashfs
Docker Image: basilisk

Inspected Size: 1082 MB

(1/10) Creating a build sandbox...
(2/10) Exporting filesystem...
(3/10) Creating labels...
./docker2singularity.sh: line 224: /addLabel.py: No such file or directory

**Comment by vsoch** [comment]
The script is intended to be run with the Docker container, not from your Macbook as you've shown above. Take a look at the README and follow the instructions, let me know if anything isn't clear.

**Comment by blairjj** [comment]
Vsoch... Yikes... *hangs head in shame*

**Comment by vsoch** [comment]
aww it's okay! Trust me, it happens to the best of us :hugs:
