### ISSUE TITLE
Issues with permissions when running on HPC

### ISSUE THREAD

**Issue by jvarada** [singularityware/docker2singularity#7]
@chrisfilo I used this container to create a singularity image from an mriqc docker container, but I am running into some problems when running it on our cluster.

I changed the mriqc Dockerfile to create the mount points to our HPC cluster, as recommended by our HPC facility:
`RUN mkdir /gpfs /spin1 /gs2 /gs3 /gs4 /gs5 /data /scratch /fdb /lscratch`

I also removed the command in mriqc's Dockerfile to set the WORKDIR to /scratch since in our HPC we don't have read/write access to all of /scratch, just to a subdir of /scratch with our username.

When I try to run the image, mriqc executes properly, but after it is done executing, it attempts to rewrite the permissions from every subfolder in /scratch. Could this be a side effect of the way permissions are set within the singularity image when converting the Docker container? I tried creating an image last week and did not have this problem, but I might have been using an older version of docker2singularity I found referenced in a google discussion group.

**Comment by jvarada** [comment]
Nvm, this was a problem with mriqc itself. Opened a bug report there.

**Comment by chrisfilo** [comment]
I'm glad you figured it out.

I'll add the mount points from your system to the script (I could make this a command line option, but I hope we can achieve some form of portability, by having all images have all necessary mount points).
